### PR TITLE
Ansible 2.7 Newly supported module

### PR DESCRIPTION
**Pull request by justjais**
- A record
- AAAA record
- CNAME record
- MX record
- NAPTR record
- PTR record
- SRV record
- TXT record

### CODE REVIEW

**Comment by justjais** [comment]
@sganesh-infoblox This PR contains all the example for newly supported modules with Ansible `2.7`. Please review and if it looks ok to you we can go ahead and merge the same for the users to refer these examples.

**Comment by justjais** [comment]
@s-giri Can you please review and merge the newly added module playbook example.

**Comment by ghost** [comment]
@justjais, changes are ok. Just one point. We're not mentioning the "view" in which we're creating the records. Do you think this should be added?

**Comment by justjais** [comment]
@s-giri, I didn't got the exact doubt as for all the modules plays `view` is not mandatory parameter.

**Comment by justjais** [comment]
@s-giri can you please merge the respective PR.

**Pull request merged**
